[package]
name = "transmission-rpc"
version = "0.3.2"
authors = ["red <red.avtovo@gmail.com>"]
edition = "2018"
repository = "https://github.com/j0rsa/transmission-rpc"
license = "MIT"
readme = "README.md"
description = "Transmission JRPC client"
keywords = ["transmission", "torrent", "jrpc"]
categories = ["api-bindings"]
include = [
    "**/*.rs",
    "Cargo.toml",
]

[dependencies]
reqwest = { version = "0.11.0", features = ["json", "rustls-tls"], default-features = false }
tokio = { version = "0.2", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
rustc-serialize = "0.3.24"
enum-iterator = "0.6.0"

dotenv = "0.15.0"
log = "0.4.8"
env_logger = "0.8.2"
