name: CI

on: 
  push:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Get Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
