name: Release

on:
  release:
    types:
      - released

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Get Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Cargo Login
        uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${{ secrets.CARGO_TOKEN }}
      - name: Cargo Publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
